### ISSUE TITLE
UDP ? 

### ISSUE THREAD

**Issue by nukadelic** [colyseus/colyseus-hx#15]
is it supported ?

**Comment by endel** [comment]
No, Colyseus uses WebSockets, which is based on TCP.

**Comment by vinhvugearinc** [comment]
realtime games require UDP though, do you have plan to make it work on UDP?

**Comment by oyed** [comment]
Real time games don't _require_ UDP, it varies depending on the type of game.

For web games, this currently isn't possible (as far as I'm aware).

**Comment by vinhvugearinc** [comment]
For some genre game that will be required, also developers don't only work on webgame.

**Comment by oyed** [comment]
I agree, as I said, it varies depending on the type of game.

Either way, we're tracking potential UDP implementations here: https://github.com/colyseus/colyseus/issues/272
