### ISSUE TITLE
Type not found : io.colyseus.Client

### ISSUE THREAD

**Issue by ccfiel** [colyseus/colyseus-hx#16]
I follow this instruction https://docs.colyseus.io/getting-started/haxe-client/
I install using this 
```
haxelib git colyseus https://github.com/colyseus/colyseus-hx.git
haxelib git haxe-ws https://github.com/colyseus/haxe-ws.git
```
but every time I run my game I got this error Type not found : io.colyseus.Client. Any idea why?
```
import io.colyseus.Client;
```

**Comment by sh-dave** [comment]
I would guess a `-lib colyseus-hx` is missing somewhere in your build scripts to actually include the library.

**Comment by ccfiel** [comment]
thanks!

**Comment by Raam124** [comment]
> I would guess a `-lib colyseus-hx` is missing somewhere in your build scripts to actually include the library.

I'm having the same issue. where should I include this exactly ??

**Comment by sh-dave** [comment]
Depends on the framework you're using. Normally you can just provide it via the commandline or the hxml to the haxe compiler.

**Comment by Raam124** [comment]
> Mostly depends on the framework you're using. Normally you can just provide it via the commandline or the hxml to the haxe compiler. If you're using openfl it should be placed somewhere in the project.xml iirc, but you have to read up on that in the openfl documentation.

Thanks
