### ISSUE TITLE
Cannot run example in Haxe 4.1.0

### ISSUE THREAD

**Issue by theRemix** [colyseus/colyseus-hx#34]
openfl 8.9.6
lime 7.7.0

`haxelib run lime test project.xml html5`
```
C:/HaxeToolkit/haxe/lib/openfl/8,9,6/src/openfl/display/Stage.hx:1426: 
characters 46-59 : haxe.CallStack has no field lastException
```

what versions will this example run in?

**Comment by serjek** [comment]
It feels like openfl needs to be updated to be compatible with haxe 4.1.0

**Comment by serjek** [comment]
I will close this as invalid, because error clearly references to `openfl` class. 
@theRemix feel free to reopen if you still think it's colyseus lib problem.
