### ISSUE TITLE
Unicode string encoding

### ISSUE THREAD

**Issue by kotwys** [colyseus/colyseus-hx#35]
Whenever I send some string including characters that take more than one byte, the server crashes with the following message:
```
Error: 4 trailing bytes
    at Object.decode (<...>/node_modules/notepack.io/lib/decode.js:262:11)
    at <Room>._onMessage (<...>/node_modules/colyseus/lib/Room.js:440:41)
    at WebSocket.emit (events.js:314:20)
```
Colyseus.js works properly in the same case. Sending Unicode string back to the client also works.

Probably string length detection doesn’t consider variable length of characters.

**Comment by endel** [comment]
Hi @kotwys, thanks for reporting! I see that you pushed a fix for this already https://github.com/kotwys/colyseus-hx/commit/33bec78bc7ac8a65a6e900fca2173e56c8fa7344

Can you confirm this works for you? Cheers!

**Comment by kotwys** [comment]
Hello @endel! Yes, that works for me. As far as I could check out different writings with JS-targeted client.
