### ISSUE TITLE
Compilation error at Schema

### ISSUE THREAD

**Issue by serjek** [colyseus/colyseus-hx#39]
haxe/haxe_libraries/colyseus/0.14.2/haxelib/src/io/colyseus/serializer/schema/Schema.hx:584: lines 584-590 : Cannot use Void as value

**Comment by serjek** [comment]
I believe it's missing `return` statement here:
```haxe
Lambda.mapi(previousValue.items, function(index, item) {
              return deletes.push({
                op: cast OPERATION.DELETE,
                field: cast index,
                dynamicIndex: cast index,
                value: null,
                previousValue: item
              });
            });
```
But I'm not sure. Adding a `return` fixes the compilation though but I can not yet tell if it works as expected.

**Comment by endel** [comment]
Thanks @serjek, that's it! I'll push this
