### ISSUE TITLE
MapSchema of primitive type does not trigger onChange for self or for parent Schema

### ISSUE THREAD

**Issue by serjek** [colyseus/colyseus-hx#40]
Map schema declared in this way:
```
class ParentSchema extends Schema {
    @:type("map","string")
    public var childMap:MapSchema<String> = new MapSchema<String>();
}
```
`onChange`, `onAdd` and `onRemove` are not trigger on neither `parent` or `childMap` when childMap changed on server.  I does not work with ArraySchema as well, see comment below.

**Comment by serjek** [comment]
Also a question, why would `ArraySchema` does not dispatch `onChange` when new item is pushed? it used to work in 0.13.x

**Comment by serjek** [comment]
my testcase:
on server
```haxe
@:type({map:STRING})
var testMap:MapSchema<String> = new MapSchema<String>();

@:type([NUMBER])
var testArray:ArraySchema<Int> = new ArraySchema<Int>();

public function new() {
	super();
	var int:Int = 0;
	new haxe.Timer(1000).run = () -> {
		var p:Player = int % 3;
		testMap.set(p, Std.string(int));
		testArray.push(int);
		if (int % 10 == 0) {
			testMap = new MapSchema<String>();
			testArray = new ArraySchema<Int>();
		}
		int ++;
	};
}
```

on client:
```haxe
@:type("map","string")
public var testMap:MapSchema<String> = new MapSchema<String>();

@:type("array","number")
public var testArray:ArraySchema<Int> = new ArraySchema<Int>();
```

handler
```haxe
//this triggers only when map or array are created with `new`
//when new value appended it is also triggered but traces just empty array
room.state.onChange = function(v) trace('Root.onChange', v); 

//following callbacks are never triggered
room.state.testMap.onChange = function(v,k) trace('Map.onChange', v,'key',k);
room.state.testMap.onAdd = function(v,k) trace('Map.onAdd', v,'key',k);
room.state.testMap.onRemove = function(v,k) trace('Map.onRemove', v,'key',k);
room.state.testArray.onChange = function(v,k) trace('Array.onChange', v,'key',k);
room.state.testArray.onAdd = function(v,k) trace('Array.onAdd', v,'key',k);
room.state.testArray.onRemove = function(v,k) trace('Array.onRemove', v,'key',k);

//Note that `room.onStateChange` returns correct state snapshot on every tick
```

**Comment by endel** [comment]
Hi @serjek, I've tried and could not reproduce this issue you described, could you please review what I've done here and check what might be happening? 👀 

The empty changes during `room.state.onChange` was actually a problem that should have been fixed here (https://github.com/colyseus/colyseus-hx/commit/98418f454a772cabf9020202399316d20a630c76#diff-0fb053d4044f0c8088a186d7b4d94305cb48f1a3d43b7d4391e0d49fd8748abeR636)

To run it locally too, you can take a look at the following:
- [there's a server using the room code you've mentioned at `examples/server`](https://github.com/colyseus/colyseus-hx/blob/master/example/server/rooms/TestRoom.ts) (I've only moved `int++` above the conditional block, to avoid resetting it in the first loop)
- [there's a barebones heaps project at `examples/heaps`](https://github.com/colyseus/colyseus-hx/tree/master/example/heaps) (to compile it run `haxe compile.js.hxml`)

The logs on this example seems to make sense to me:

```
src/Main.hx:17: Root.onChange, [{
		op : 128, 
		field : testMap, 
		dynamicIndex : null, 
		value : MapSchema (0, __refId => 1) {  }, 
		previousValue : MapSchema (0, __refId => undefined) {  }
	},{
		op : 128, 
		field : testArray, 
		dynamicIndex : null, 
		value : ArraySchema(0) { __refId => 2,  } , 
		previousValue : ArraySchema(0) { __refId => undefined,  } 
	}]
Log.hx:66 src/Main.hx:21: Map.onAdd, 0, key, 0
Log.hx:66 src/Main.hx:25: Array.onAdd, 0, key, 0
Log.hx:66 src/Main.hx:21: Map.onAdd, 1, key, 1
Log.hx:66 src/Main.hx:25: Array.onAdd, 1, key, 1
Log.hx:66 src/Main.hx:21: Map.onAdd, 2, key, 2
Log.hx:66 src/Main.hx:25: Array.onAdd, 2, key, 2
Log.hx:66 src/Main.hx:20: Map.onChange, 3, key, 0
Log.hx:66 src/Main.hx:25: Array.onAdd, 3, key, 3
Log.hx:66 src/Main.hx:20: Map.onChange, 4, key, 1
Log.hx:66 src/Main.hx:25: Array.onAdd, 4, key, 4
Log.hx:66 src/Main.hx:20: Map.onChange, 5, key, 2
Log.hx:66 src/Main.hx:25: Array.onAdd, 5, key, 5
Log.hx:66 src/Main.hx:20: Map.onChange, 6, key, 0
Log.hx:66 src/Main.hx:25: Array.onAdd, 6, key, 6
Log.hx:66 src/Main.hx:20: Map.onChange, 7, key, 1
Log.hx:66 src/Main.hx:25: Array.onAdd, 7, key, 7
Log.hx:66 src/Main.hx:20: Map.onChange, 8, key, 2
Log.hx:66 src/Main.hx:25: Array.onAdd, 8, key, 8
Log.hx:66 src/Main.hx:17: Root.onChange, [{
		op : 128, 
		field : testMap, 
		dynamicIndex : null, 
		value : MapSchema (0, __refId => 3) {  }, 
		previousValue : MapSchema (3, __refId => 1) { 0 => 6, 1 => 7, 2 => 8 }
	},{
		op : 128, 
		field : testArray, 
		dynamicIndex : null, 
		value : ArraySchema(0) { __refId => 4,  } , 
		previousValue : ArraySchema(9) { __refId => 2, 0, 1, 2, 3, 4, 5, 6, 7, 8 } 
	}]
Log.hx:66 src/Main.hx:22: Map.onRemove, 6, key, 0
Log.hx:66 src/Main.hx:22: Map.onRemove, 7, key, 1
Log.hx:66 src/Main.hx:22: Map.onRemove, 8, key, 2
Log.hx:66 src/Main.hx:26: Array.onRemove, 0, key, 0
Log.hx:66 src/Main.hx:26: Array.onRemove, 1, key, 1
Log.hx:66 src/Main.hx:26: Array.onRemove, 2, key, 2
Log.hx:66 src/Main.hx:26: Array.onRemove, 3, key, 3
Log.hx:66 src/Main.hx:26: Array.onRemove, 4, key, 4
Log.hx:66 src/Main.hx:26: Array.onRemove, 5, key, 5
Log.hx:66 src/Main.hx:26: Array.onRemove, 6, key, 6
Log.hx:66 src/Main.hx:26: Array.onRemove, 7, key, 7
Log.hx:66 src/Main.hx:26: Array.onRemove, 8, key, 8
Log.hx:66 src/Main.hx:21: Map.onAdd, 10, key, 1
Log.hx:66 src/Main.hx:25: Array.onAdd, 10, key, 0
...
```

**Comment by serjek** [comment]
Hey thanks for checking! Sorry for improper report, it turns out that it works if `MapSchema` and `ArraySchema` are created in **root** state, but to get it working in child schema I need to attach events after first onStateChange in the room. which is a bit inconvenient but at least I got it working now:

```haxe
var onStateChange:Dynamic;
onStateChange = (s) -> {
    //listeners
    ....
    room.onStateChange -= onStateChange;
};
room.onStateChange += onStateChange;
```

For me it seem to be inconsistent behaviour because if those schemas belong to root then I don't need to wait until they are actually created. Let me know if this is expected or this is a bug that we can fix.

**Comment by endel** [comment]
Thanks a lot for noticing @serjek, I've done a workaround specifically for the Haxe client on this commit https://github.com/colyseus/colyseus-hx/commit/7437255ae6d93d395c9fff22d5304aef76e04628#diff-0fb053d4044f0c8088a186d7b4d94305cb48f1a3d43b7d4391e0d49fd8748abeR385, which should be ported back to all other clients soon. 

I'd love it for the next iteration of the schema (in a year from now or so?) if we can separate the raw data structures from callback structures because having them combined right now does not seem to be correct (practically and semantically)

**Comment by endel** [comment]
Please let me know if that fixes it for you, or if you have any other consideration! Feel free to reopen if you feel the need to. [Version 0.14.7](https://lib.haxe.org/p/colyseus/) has been published already :)
