### ISSUE TITLE
Wont compile with hl as target

### ISSUE THREAD

**Issue by tobias1012** [colyseus/colyseus-hx#7]

**Comment by endel** [comment]
thanks for reporting @tobias1012, I'll check this soon

**Comment by endel** [comment]
hey @tobias1012, I've just pushed a fix for the `hl` target and Haxe 4.0! let me know if it works for you!

**Comment by tobias1012** [comment]
Wow that was quick! I'm gonna test it tommorow, thanks!

søn. 10. mar. 2019 22.50 skrev Endel Dreyer <notifications@github.com>:

**Comment by tobias1012** [comment]
hi, i've been unable to test it, right now i can only install via haxelib

**Comment by endel** [comment]
hey @tobias1012, can you install it thorugh git using this?

```
haxelib git colyseus https://github.com/colyseus/colyseus-hx.git
```

**Comment by tobias1012** [comment]
Yeah it works, thanks
